# Generated by Django 4.2 on 2025-05-26 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), django.core.validators.MaxValueValidator(5242880)]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REACHED_OUT', 'Reached Out')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['state', 'created_at'], name='leads_lead_state_7e1409_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email', 'state'], name='leads_lead_email_f390a9_idx'),
        ),
    ]
